<a href="https://colab.research.google.com/github/TajbeerAhamed/Data-Mining-Lab-Assignments/blob/main/Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries and dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data_Mining_LAb/Assignments/Project_2/heart_disease.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,high,1,3,high,medium,1,0,medium,0,high,0,0,1,1
1,low,1,2,medium,medium,0,1,high,0,high,0,0,2,1
2,low,0,1,medium,low,0,0,high,0,high,2,0,2,1
3,medium,1,1,low,medium,0,1,high,0,medium,2,0,2,1
4,medium,0,0,low,high,0,1,high,1,medium,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,medium,0,0,high,medium,0,1,low,1,medium,1,0,3,0
299,low,1,3,low,high,0,1,low,0,medium,1,0,3,0
300,high,1,0,high,low,1,1,low,0,high,1,2,3,0
301,medium,1,0,medium,low,0,1,low,1,medium,1,1,3,0
302,medium,0,1,medium,medium,0,0,high,0,low,1,1,2,0

In [ ]:
# Encoding Dataset
import pandas as pd
df_encoded = pd.get_dummies(df, columns=df.columns)
df_encoded

,age_high,age_low,age_medium,sex_0,sex_1,cp_0,cp_1,cp_2,cp_3,trestbps_high,...,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3,target_0,target_1
0,True,False,False,False,True,False,False,False,True,True,...,False,False,False,False,False,True,False,False,False,True
1,False,True,False,False,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
2,False,True,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,False,False,True,False,True,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
4,False,False,True,True,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,True,True,False,True,False,False,False,True,...,False,False,False,False,False,False,False,True,True,False
299,False,True,False,False,True,False,False,False,True,False,...,False,False,False,False,False,False,False,True,True,False
300,True,False,False,False,True,True,False,False,False,True,...,False,True,False,False,False,False,False,True,True,False
301,False,False,True,False,True,True,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False
302,False,False,True,True,False,False,True,False,False,False,...,True,False,False,False,False,False,True,False,True,False

In [ ]:
# Frequent itemset generation
frequent_itemsets = apriori(df_encoded, min_support=0.3,
use_colnames=True)
print(frequent_itemsets)

     support                            itemsets
0   0.343234                          (age_high)
1   0.313531                           (age_low)
2   0.343234                        (age_medium)
3   0.316832                             (sex_0)
4   0.683168                             (sex_1)
..       ...                                 ...
88  0.376238         (exang_0, thal_2, target_1)
89  0.336634            (ca_0, thal_2, target_1)
90  0.323432    (ca_0, fbs_0, exang_0, target_1)
91  0.330033  (fbs_0, exang_0, thal_2, target_1)
92  0.303630     (ca_0, fbs_0, thal_2, target_1)

[93 rows x 2 columns]

In [ ]:
# Association rule generation
num_itemsets = len(frequent_itemsets)
rules = association_rules(frequent_itemsets, metric="confidence",
min_threshold=0.7, num_itemsets = num_itemsets)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(cp_0),(sex_1),0.471947,0.683168,0.343234,0.727273,1.064559,1.0,0.020815,1.161716,0.114844,0.422764,0.139205,0.614844
1,(sex_1),(fbs_0),0.683168,0.851485,0.574257,0.840580,0.987192,1.0,-0.007450,0.931593,-0.039337,0.597938,-0.073430,0.757499
2,(restecg_0),(sex_1),0.485149,0.683168,0.339934,0.700680,1.025633,1.0,0.008496,1.058506,0.048544,0.410359,0.055272,0.599132
3,(thal_3),(sex_1),0.386139,0.683168,0.336634,0.871795,1.276106,1.0,0.072836,2.471287,0.352467,0.459459,0.595353,0.682274
4,(target_0),(sex_1),0.455446,0.683168,0.376238,0.826087,1.209200,1.0,0.065092,1.821782,0.317703,0.493506,0.451087,0.688406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,"(ca_0, thal_2, target_1)",(fbs_0),0.336634,0.851485,0.303630,0.901961,1.059280,1.0,0.016992,1.514851,0.084361,0.343284,0.339869,0.629275
95,"(fbs_0, thal_2, target_1)",(ca_0),0.376238,0.577558,0.303630,0.807018,1.397293,1.0,0.086331,2.189019,0.455832,0.467005,0.543174,0.666366
96,"(ca_0, thal_2)","(fbs_0, target_1)",0.376238,0.468647,0.303630,0.807018,1.722016,1.0,0.127308,2.753375,0.672188,0.560976,0.636809,0.727452
97,"(ca_0, target_1)","(fbs_0, thal_2)",0.429043,0.481848,0.303630,0.707692,1.468704,1.0,0.096897,1.772625,0.558934,0.500000,0.435865,0.668915
98,"(thal_2, target_1)","(ca_0, fbs_0)",0.429043,0.511551,0.303630,0.707692,1.383424,1.0,0.084153,1.671009,0.485423,0.476684,0.401559,0.650620

In [ ]:
# Generate the top 10 association rules based on confidence and lift
rules = rules.sort_values(by=['confidence', 'lift'], ascending=False)
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
8,(trestbps_low),(fbs_0),0.333333,0.851485,0.313531,0.940594,1.104651,1.0,0.029703,2.500000,0.142105,0.359848,0.600000,0.654406
54,"(ca_0, thal_2)",(fbs_0),0.376238,0.851485,0.343234,0.912281,1.071399,1.0,0.022874,1.693069,0.106838,0.388060,0.409357,0.657691
94,"(ca_0, thal_2, target_1)",(fbs_0),0.336634,0.851485,0.303630,0.901961,1.059280,1.0,0.016992,1.514851,0.084361,0.343284,0.339869,0.629275
75,"(ca_0, thal_2)",(target_1),0.376238,0.544554,0.336634,0.894737,1.643062,1.0,0.131752,4.326733,0.627451,0.576271,0.768879,0.756459
45,"(ca_0, exang_0)",(fbs_0),0.432343,0.851485,0.386139,0.893130,1.048908,1.0,0.018005,1.389675,0.082141,0.430147,0.280407,0.673309
63,"(slope_2, thal_2)",(exang_0),0.336634,0.673267,0.300330,0.892157,1.325115,1.0,0.073686,3.029703,0.369854,0.423256,0.669935,0.669118
15,(ca_0),(fbs_0),0.577558,0.851485,0.511551,0.885714,1.040199,1.0,0.019769,1.299505,0.091482,0.557554,0.230476,0.743245
57,"(ca_0, target_1)",(fbs_0),0.429043,0.851485,0.379538,0.884615,1.038909,1.0,0.014214,1.287129,0.065594,0.421245,0.223077,0.665176
92,"(ca_0, fbs_0, thal_2)",(target_1),0.343234,0.544554,0.303630,0.884615,1.624476,1.0,0.116721,3.947195,0.585318,0.519774,0.746656,0.721096
16,(thal_2),(fbs_0),0.547855,0.851485,0.481848,0.879518,1.032922,1.0,0.015358,1.232673,0.070493,0.525180,0.188755,0.722705

In [ ]:
# Step 3: Sort rules by lift in descending order and select top 10
top_10_rules = rules.sort_values(by=["confidence", "lift"],
ascending=False).head(10)

In [ ]:
# Step 4: Display the top 10 rules
print(top_10_rules[['confidence', 'lift']])

    confidence      lift
8     0.940594  1.104651
54    0.912281  1.071399
94    0.901961  1.059280
75    0.894737  1.643062
45    0.893130  1.048908
63    0.892157  1.325115
15    0.885714  1.040199
57    0.884615  1.038909
92    0.884615  1.624476
16    0.879518  1.032922